# Site settings
baseurl = "http://www.debashish.com/"
languageCode = "en-us"
title = "Debashish Chakrabarty Web Home"
theme = "dc-hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-50884-12"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# The icons are represented by their corresponding CSS class.

	# Metadata for search engines
	name = "Debashish Chakrabarty"
	description = "Hindi Blogger, Podcaster, Software Professional"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	#email = "your@email.com"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "Debashish Chakrabarty"				
		portfolio = "Creations"	
		about = "About"		
		#team = "Team"
		#contact = "Contact"
		#services = "Services"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://nullpointer.debashish.com"
        name = "Null Pointer"
        weight = 10
		
	# postpended links
    [[menu.postpend]]
        url = "http://nuktachini.debashish.com"
        name = "NuktaChini"
        weight = 11
	
	# postpended links
    [[menu.postpend]]
        url = "http://www.samayiki.com"
        name = "Samayiki"
        weight = 11
		
	# postpended links
    [[menu.postpend]]
        url = "http://www.podbharati.com"
        name = "Podbharati"
        weight = 11

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome To My Web Home!"
		subtitle = "Nice to see you here"
		buttonText = "Tell me about yourself"


	# Services section
	[params.services]
        enable = false
		title = "Services"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-shopping-cart"
                title = "E-Commerce"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Responsive Design"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Web"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "My Creations"
		subtitle = "Here are some of my hobby projects, many of them now defunct :("

		[params.portfolio.modal]
            client = "URL"
            date = "Period"
            category = "Topic"
            buttonText = "Go Back!"


    # About section
	[params.about]
        enable = true
		timeline = false
		title = "About Debashish"
		subtitle = "Hindi Blogger, Podcaster, Software TPM"
		subtitle2 = "Curious to know more? Please [click here](http://nullpointer.debashish.com/about-the-author)."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			#date = "2009-2011"
			title = "Bhopali Banarasi"
			description = "I was born at [Varanasi](//en.wikipedia.org/wiki/Varanasi), situated on the banks of the holy Ganga, although in all practical sense I have been a Bhopali, for I was brought up [here](//en.wikipedia.org/wiki/Bhopal), in the capital city of India's erstwhile largest state - Madhya Pradesh. I did my schooling from Raman Higher Secondary School, part of the education society schools of Public sector giant [BHEL](//www.bhel.com) and named after the renowned Indian [Nobel laureate](//en.wikipedia.org/wiki/C._V._Raman). I attained my Bachelors in Electrical engineering from [Awadhesh Pratap Singh University](//apsurewa.ac.in/), [Rewa](//en.wikipedia.org/wiki/Rewa,_Madhya_Pradesh) (land of the white tigers). Apart from this, I have been attained PG diplomas in Operations and Marketing Management (from IGNOU, Delhi) and PG Diploma in Advanced Computing (from CDAC)." 

		[[params.about.events]]
			img = "2.jpg"
			#date = "2009-2011"
			title = "Those Geocities days"
			description = "I am a Software Consultant based at Pune (and an erstwhile blogger and podcaster). Have been on the Internet since the [Yahoo Geocities](//www.geocities.ws/debuchakrabarty/) days; opened my Blogger account in October 2002. On Geocities I hosted couple of sites including an [Amitabh Bachchan fan site](, a site for Java lovers called [Wah Java!](//web.archive.org/web/20060128012132/http://www.geocities.com/wahjava/)."
			
		[[params.about.events]]	
			img = "3.jpg"
			#date = "2009-2011"
			title = "Those Geocities days"
			description = "I have English blog **Null Pointer** and a Hindi one **NuktaChini**, though most of his blogging has now been replaced by micro-blogging at [Twitter](//twitter.com/dchucks)."



	# Team section
	[params.team]
        enable = false
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]


	# Client section
    [params.clients_list]
        enable = false

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

	# Contact section
	[params.contact]
        enable = false
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Created with Hugo & Github pages"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "http://twitter.com/dchucks"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://in.linkedin.com/in/debashishc"
			
		[[params.footer.social]]
			icon = "fa-flickr"
			link = "http://www.flickr.com/people/dchucks/"
			
		[[params.footer.social]]
			icon = "fa-podcast"
			link = "http://podbharati.com/"
			
		[[params.footer.social]]
			icon = "fa-wordpress"
			link = "http://www.samayiki.com/"

		[[params.footer.quicklinks]]
			text = "Views my own or authors', not of my employer."
			link = "http://nullpointer.debashish.com/about/disclaimer"
